### ISSUE TITLE
Rx-DOM dependency

### ISSUE THREAD

**Issue by roganov** [trxcllnt/rxjs-easing#4]
Does this library really need to depend on Rx-DOM?

**Comment by trxcllnt** [comment]
@roganov It uses the RequestAnimationFrameScheduler to schedule each animation tick, but I suppose that could be parameterized.

**Comment by roganov** [comment]
@trxcllnt Thanks, I already discovered that, but now I have another question/problem concerning animations smoothness. I'll open a new issue if you don't mind.
