### ISSUE TITLE
Animation with rxjs-easing is not smooth

### ISSUE THREAD

**Issue by roganov** [trxcllnt/rxjs-easing#5]
`rxjs-easing` uses hard-coded animation frame rate (30fps), which cases jerks on more powerful machines. Here is a [jsfiddle](http://jsfiddle.net/yucsj6jL/2/) where this effect can be seen (scrolling using both jquery and explicit RAF scheduler is smoother that `rxjs-easing`.

**Comment by trxcllnt** [comment]
@roganov upgrading this lib to [ReactiveX/RxJS](https://github.com/ReactiveX/RxJS) will fix this.
